# Used with patterns.yaml as input.

VarName:             '[(validate.rules).string.pattern = "^[a-zA-Z_][a-zA-Z0-9_]*$"]'
AccountName:         '[(validate.rules).string.pattern = "^[a-zA-Z][0-9a-zA-Z_-]+$"]'
EventSourceName:     '[(validate.rules).string.pattern = "^[a-zA-Z][0-9a-zA-Z_-]+$"]'
EventSourceID:       '[(validate.rules).string.pattern = "^[a-zA-Z][0-9a-zA-Z_-]+\\.[a-zA-Z][0-9a-zA-Z_-]+$"]'
EventID:             '[(validate.rules).string.pattern = "^E[0-9a-f]+$"]'
FunctionID:          '[(validate.rules).string.pattern = "^F[0-9a-f.]+$"]'
Lang:                '[(validate.rules).string.pattern = "^[0-9a-zA-Z_-]+$"]'
ModuleName:          '[(validate.rules).string.pattern = "^.+"]'
PluginID:            '[(validate.rules).string.pattern = "^[a-zA-Z][0-9a-zA-Z_-]+\\.[a-zA-Z][0-9a-zA-Z_-]+$"]'
ProjectID:           '[(validate.rules).string.pattern = "^[a-zA-Z][0-9a-zA-Z_-]+\\.[a-zA-Z0-9_-]+$"]'
RunID:               '[(validate.rules).string.pattern = "^R[0-9a-f.]+$"]'
LitterBoxID:         '[(validate.rules).string.pattern = "^[a-zA-Z0-9_-]+$"]'

MaybeVarName:         '[(validate.rules).string = {ignore_empty:true, pattern: "^[a-zA-Z_][a-zA-Z0-9_]*$" }]'
MaybeAccountName:     '[(validate.rules).string = {ignore_empty:true, pattern: "^[a-zA-Z][0-9a-zA-Z_-]+$" }]'
MaybeProjectID:       '[(validate.rules).string = {ignore_empty:true, pattern: "^[a-zA-Z][0-9a-zA-Z_-]+\\.[a-zA-Z0-9_-]+$" }]'
MaybeEventSourceName: '[(validate.rules).string = {ignore_empty:true, pattern: "^[a-zA-Z][0-9a-zA-Z_-]+$" }]'
MaybeEventSourceID:   '[(validate.rules).string = {ignore_empty:true, pattern: "^[a-zA-Z][0-9a-zA-Z_-]+\\.[a-zA-Z][0-9a-zA-Z_-]+$" }]'
MaybeLitterBoxID:     '[(validate.rules).string = {ignore_empty:true, pattern: "^[a-zA-Z0-9_-]+$" }]'

RepeatedAccountName:     '[(validate.rules).repeated.items.string.pattern = "^[a-zA-Z][0-9a-zA-Z_-]+$"]'
RepeatedEventID:         '[(validate.rules).repeated.items.string.pattern = "^E[0-9a-f]+$"]'
RepeatedEventSourceName: '[(validate.rules).repeated.items.string.pattern = "^[a-zA-Z][0-9a-zA-Z_-]+$"]'
RepeatedEventSourceID:   '[(validate.rules).repeated.items.string.pattern = "^[a-zA-Z][0-9a-zA-Z_-]+\\.[a-zA-Z][0-9a-zA-Z_-]+$"]'
RepeatedPluginID:        '[(validate.rules).repeated.items.string.pattern = "^[a-zA-Z][0-9a-zA-Z_-]+\\.[a-zA-Z][0-9a-zA-Z_-]+$"]'
RepeatedPredecl:         '[(validate.rules).repeated.items.string.pattern = "^[a-zA-Z_][a-zA-Z0-9_]*$"]'
RepeatedProjectID:       '[(validate.rules).repeated.items.string.pattern = "^[a-zA-Z][0-9a-zA-Z_-]+\\.[a-zA-Z0-9_-]+$"]'
RepeatedVarName:         '[(validate.rules).repeated.items.string.pattern = "^[a-zA-Z_][a-zA-Z0-9_]*$"]'

VarMap: '[(validate.rules).map={no_sparse: true, keys:{string:{pattern: "^[a-zA-Z_][a-zA-Z0-9_]*$"}}}]'
